# Generated by Django 3.2.5 on 2021-07-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210727_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=models.TextField(),
        ),
    ]
