# Generated by Django 3.2.5 on 2021-07-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpage',
            name='intro_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
