# Generated by Django 3.2.5 on 2021-08-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0014_formcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindex',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogindex',
            name='topic',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FormComment',
        ),
    ]
